# Generated by Django 5.0.7 on 2024-08-04 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_unit_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='name',
        ),
    ]
